[tool.black]
line-length=120

[tool.flake8]
line-length=120

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov=terrapyn --cov-branch --cov-report term-missing  -vv --color=yes"
#  --cov-fail-under 100
