name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    # Skip this job if it's a pre-release
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Build package
        run: make build
      - name: Publish to PyPI
        run: uv publish --index pypi