name: Publish to PyPI

on:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - name: Install poetry
          run: pip install poetry
        - name: Bump version number
          run: poetry version ${{ github.event.release.tag_name }}
        - name: Build package
          run: poetry build
        - name: Publish package
          run: |
            poetry config pypi-token.pypi ${{ secrets.TEST_PYPI_API_TOKEN }}
            poetry publish
