name: Test Code Quality

on:
  push:
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  test-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          enable-cache: true
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Lint and format with Ruff
        run: |
          make lint
          make format
      - name: Unit & Coverage test with pytest
        run: make test
      - name: Update Coverage Badge
        run: |
          uv add readme-coverage-badger
          uv run readme-cov
