name: Publish to Test PyPI

on:
  release:
    types: [prereleased]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@main
        - name: Set up Python 3.10
          uses: actions/setup-python@v1
          with:
            python-version: 3.10

        - name: Install dependencies
          run: pip install wheel
        - name: Build package
          run: python setup.py sdist bdist_wheel
        - name: Publish package to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
