name: Test Code Quality

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Lint with Flake8
        run: flake8 --extend-ignore=D1,D2,D4,I0,I1,I2 terrapyn/ tests/
      - name: Format with Black
        run: black --check terrapyn/ tests/
      # - name: Type Check with MyPy
      #   run: mypy --strict --config-file=mypy.ini terrapyn/
      - name: Test & Coverage with Pytest
        run: pytest terrapyn/ tests/
      - name: Generate coverage badge
        run: coverage-badge -f .github/coverage.svg
