name: Test Code Quality

on:
  push:
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.5
          cache: true
          auth-host: prefix.dev
          python-version: '3.11'
      - name: Install dependencies
        run: pixi install 
      - name: Check style with Ruff
        run: pixi run ruff terrapyn/ tests/ --extend-ignore=D1,D2,D4,TID
      - name: Check format with black
        run: pixi run black --check terrapyn/ tests/
      - name: Unit & Coverage test with pytest
        run: pixi run pytest terrapyn/ tests/
      - name: Update Coverage Badge
        run: |
          pip install readme-coverage-badger
          readme-cov