name: Test Code Quality

on:
  push:
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Lint with Flake8
        run: |
          flake8 terrapyn/ tests/ --extend-ignore=D1,D2,D4,I0,I1,I2
      - name: Format with Black
        run: black --check terrapyn/ tests/
      - name: Run tests
        run: |
          pip install pytest-json-report
          pytest --cov=terrapyn --json-report --json-report-summary --json-report-file=./coverage/coverage-summary.json terrapyn/ tests/
      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main
