name: Test Code Quality

on:
  push:
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Lint with Flake8
        run: |
          flake8 terrapyn/ tests/ --extend-ignore=D1,D2,D4,I0,I1,I2
      - name: Format with Black
        run: black --check terrapyn/ tests/
      - name: Run tests
        run: pytest terrapyn/ tests/
      - name: Update Coverage Badge
        run: |
          pip install readme-coverage-badger
          readme-cov
          # pip install genbadge[all]
          # coverage xml -o ./reports/coverage/coverage.xml
          # genbadge coverage -i ./reports/coverage/coverage.xml -o ./reports/coverage/coverage-badge.svg
