name: Test Code Quality

on:
  push:
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.5
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - name: Install dependencies
        run: pixi install
      - name: Lint and format with Ruff
        run: pixi run ruff check terrapyn/ tests/
      - name: Unit & Coverage test with pytest
        run: pixi run pytest terrapyn/ tests/
      - name: Update Coverage Badge
        run: |
          pip install readme-coverage-badger
          readme-cov
