name: Test Code Quality

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:

  miniconda:
    name: Miniconda ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Set-up MiniConda environment
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
            activate-environment: terrapyn
            environment-file: environment.yml
            python-version: 3.9
            auto-activate-base: false
        run: conda info
      - name: Lint with Flake8
        run: flake8 --extend-ignore=D1,D2,D4,I0,I1,I2 terrapyn/ tests/
      - name: Format with Black
        run: black --check terrapyn/ tests/
      # - name: Type Check with MyPy
      #   run: mypy --strict --config-file=mypy.ini terrapyn/
      - name: Test & Coverage with Pytest
        run: pytest terrapyn/ tests/
      - name: Generate coverage badge
        run: coverage-badge -f -o .github/coverage.svg
