name: Test Code Quality

on:
  push:
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Check style with Ruff
        run: poetry run ruff terrapyn/ tests/ --extend-ignore=D1,D2,D4,TID
      - name: Check format with black
        run: poetry run black --check terrapyn/ tests/
      - name: Unit & Coverage test with pytest
        run: poetry run pytest terrapyn/ tests/
      - name: Update Coverage Badge
        run: |
          pip install readme-coverage-badger
          readme-cov
